[workspace]
resolver = "2"
members = [
    "crates/matsya-app",
    "crates/matsya-common",
]


[workspace.dependencies]
thiserror = { version = "1.0.64"}
async-trait = { version = "0.1.83"}
config = { version = "0.14.0"}
tokio = { version = "1.37.0"}
